name: static gh-pages

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '10,30,50 * * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
    - name: checkout
      uses: actions/checkout@v2
      with:
        depth: 0
    - name: install
      run: |-
        npm install
    - name: cache
      run: |-
        npm run cache
    - name: cat cache.json
      run: |-
        cat cache.json
    - name: static
      run: |-
        npm run static
    - name: gh-pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        publish_dir: ./_site
        github_token: ${{ secrets.GITHUB_TOKEN }}
    # - name: Commit and push if it changed
    #   run: |-
    #     git config user.name "Automated"
    #     git config user.email "actions@users.noreply.github.com"
    #     git add -A
    #     timestamp=$(date -u)
    #     git commit -m "Latest data: ${timestamp}" || exit 0
    #     git push
